# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Zip Logic App. 

on:
  - push 
  - workflow_dispatch 

jobs:
   logic_app_build: 
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}


    - name: Generate Connections
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Scripts/Generate-Connections.ps1 -resourceGroup 'ARMLaDemo'
        azPSVersion: '3.1.0'

      