# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Logic App/Connnectors resources and build and push workflows. 

on:
  - push 
  - workflow_dispatch 

jobs:
   logic_app_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Generate Connections
      shell: pwsh
      run: |
        Scripts/Generate-Connections.ps1
      